version: '3.8'

services:
  react-app:
    image: somniac2103/react-homepage:latest
    container_name: react-app
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - web

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./404.html:/usr/share/nginx/html/404.html:ro
    depends_on:
      - react-app
    networks:
      - web

  postgresql-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /opt/backups/postgres:/backups
    ports:
      - "5432:5432" 
    networks:
      - web

volumes:
  postgres_data:


networks:
  web:
    driver: bridge
